// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package hashtable

import "fmt"

type HashTable struct {
	items []int
}

func (ht *HashTable) Init() {
	fmt.Println("Initializing")
	a := make([]int, 0, 10)
	ht.items = a
	fmt.Println(len(ht.items), cap(ht.items))
}
